version: "3.7"
services:
  go-crud:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["./main"]
    # volumes:
    #   - .:/app
    restart: always
    networks:
      - go-crud-net
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - go-crud-net

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   # environment:
  #   #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #   #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   networks:
  #     - go-crud-net

networks:
  go-crud-net:
    driver: bridge
